project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "R___Studio"
  draft-mode: gone
  navbar:
    search: true
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resources"
        href: resources/resources.qmd
      - text: "Guides"
        href: blog/index.qmd
        
  sidebar: 
    - title: "Resources"
      style: "docked"
      background: light
      contents:
        - resources/resources.qmd
        - section: "Data Analysis"
          contents:
              - resources/analysis_outputs/downloadable_descriptive_and_exploratory_outputs.qmd
        - section: "Survey Design"

format:
  html:
    theme:
        light: [flatly, scss/light.scss]
    css: scss/styles.css
    toc: true

editor: visual
